### ISSUE TITLE
Impossible to delete Homkit switch

### ISSUE THREAD

**Issue by DrasticKoba** [entmike/homebridge-cmdaccessory#6]
Hello,
I uninstalled the plugin cause i didn’t need it anymore but whatever i do the switch remains in the Home app and it’s impossible to get rid of it. Do you have an hint ? Thnx.

**Comment by phenotypic** [comment]
You might have to delete the "cachedAccessories" file in your "accessories" folder

**Comment by DrasticKoba** [comment]
Thnx it worked. Was beginning to get crazy about it.
